# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('web', models.CharField(max_length=150)),
                ('webName', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('locationName', models.CharField(max_length=100)),
                ('onsales', models.CharField(max_length=1)),
                ('price', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=20)),
                ('lon', models.CharField(max_length=20)),
            ],
        ),
    ]
